/**
 * Inputs the darwin/linux golden (posix-golden.json) was captured on, from the
 * code as it was before the Windows paths lot (windows 4b26873f). The golden is
 * data, never regenerated by the code it judges.
 */

/** Directories that exist, with every parent. */
const layout = [
  '/Users/charlie/Documents/myproject',
  '/Users/charlie/Documents/octav-frontend-lite',
  '/Users/charlie/Documents/docs.octav.fi',
  '/Users/charlie/Documents/my-app.v2',
  '/Users/charlie/Documents/octav-server',
  '/Users/charlie/Documents/octav/server',
  '/Users/noah/my_proj',
  '/Users/noah/My Project',
  '/Users/noah/.claude/worktrees',
  '/Users/noah/Tars/.worktrees/feat/x',
  '/home/dev/src/a.b_c-d',
  '/private/var/folders/7k/2b9_w1xs/T/tars-e2e-abc/projects/tars',
];

const paths = [
  ...layout,
  '/Users/noah/Tars',
  '/Users/noah/Tars/',
  '/Users/noah/Tars//',
  '/Users/noah/Tars/worktrees/feat',
  '/Users/noah/Tars/.worktrees',
  '/Users/noah/Tars/not.worktrees/x',
  '/Users/noah/a@b+c(d)',
  '/Users/noah/café',
  '/',
  '',
  'relative/dir',
  '/Users/noah/a:b\\c',
];

/** Folder names: each path encoded both ways the code has known, plus names no path gives. */
const dirNames = [
  ...new Set([
    ...layout.map(p => p.replace(/[/.]/g, '-')),
    ...layout.map(p => p.replace(/[^a-zA-Z0-9]/g, '-')),
    '-Users-nonexistent-path',
    '-Users',
    '-',
    '',
    'C--Users-nicol-Documents-Claude-Project-Tars',
    '-Users-noah--claude-worktrees',
  ]),
];

/** (own, asked) pairs for the path comparisons. */
const pairs: Array<[string, string]> = [
  ['/Users/noah/Tars', '/Users/noah/Tars'],
  ['/Users/noah/Tars', '/Users/noah/Tars/'],
  ['/Users/noah/Tars/', '/Users/noah/Tars'],
  ['/Users/noah/Tars', '/Users/noah/Tars/.worktrees/feat-x'],
  ['/Users/noah/Tars', '/Users/noah/Tars-other'],
  ['/Users/noah/Tars', '/Users/noah/tars'],
  ['/Users/noah/Tars', '/Users/noah'],
  ['/Users/noah/Tars', '/Users/noah/Tars/../other'],
  ['/Users/noah/Tars', '/Users/noah/Tars//x'],
  ['/', '/anything'],
  ['/', '/'],
  ['', ''],
  ['/Users/noah/Tars', ''],
  ['/Users/noah/Tars', 'Users/noah/Tars'],
];

export const POSIX_CORPUS = { layout, paths, dirNames, pairs };
