import { describe, it, expect, afterAll, afterEach } from 'vitest';
import { spawn, spawnSync, type ChildProcess } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { pathToFileURL } from 'node:url';

/**
 * hooks/statusline.mjs: the Claude Code status line on Windows (audit A15),
 * doing what the bash one generated by electron/utils/statusline.ts does. The
 * Usage page reads the two files it writes, so on Windows its figures stayed
 * empty while the bash one could not run.
 *
 * How it can fail, written before it existed:
 *  1. rate-limits.json not written, or not as the bash one writes it (the
 *     compact `rate_limits` object and a newline), or written when absent.
 *  2. token-stats.json entry not {in, out, cost, model, extra, date,
 *     provider}; other sessions lost; a file that is not one JSON object not
 *     started again from {}.
 *  3. Written in place rather than beside itself and renamed; a tmp left over.
 *  4. The lock ignored: concurrent renders lose each other's sessions. A lock
 *     older than 5s never cleared. A fresh lock held by another render
 *     overridden instead of skipping this write, as the bash does.
 *  5. Its own lock left behind.
 *  6. A status line other than the bash one (colours, bar, rounding: awk
 *     prints 2500 tokens as "2k", round-half-even, not "3k").
 *  7. A crash on missing fields, or a token-stats entry for no session.
 *  8. Anything written outside ~/.dorothy of the HOME it runs in.
 *  9. Its lock released twice: once when its write is done, and again as it
 *     exits, which removes the lock another render has taken in between. Two
 *     renders then hold it at once, both read the same file, and the last to
 *     rename drops the other's session (seen on Windows, 2026-09-26: test 4
 *     red, and 5 sessions lost in 250 rounds of six renders).
 */

const SCRIPT = path.join(__dirname, '../../hooks/statusline.mjs');
const S = 'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee';
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'tars-statusline-'));
afterAll(() => fs.rmSync(tmp, { recursive: true, force: true }));

function freshHome(): string {
  const home = fs.mkdtempSync(path.join(tmp, 'home-'));
  fs.mkdirSync(path.join(home, '.dorothy'));
  return home;
}

function render(home: string, payload: unknown, env: Record<string, string> = {}): Promise<{ code: number | null; out: string; err: string }> {
  return new Promise((resolve, reject) => {
    const cleanEnv: NodeJS.ProcessEnv = {};
    for (const [k, v] of Object.entries(process.env)) if (!/^(CLAUDE_|DOROTHY_)/.test(k)) cleanEnv[k] = v;
    const child = spawn(process.execPath, [SCRIPT], {
      cwd: home,
      env: { ...cleanEnv, HOME: home, USERPROFILE: home, ...env },
      windowsHide: true,
    });
    let out = '';
    let err = '';
    child.stdout.setEncoding('utf8');
    child.stderr.setEncoding('utf8');
    child.stdout.on('data', d => { out += d; });
    child.stderr.on('data', d => { err += d; });
    child.on('error', reject);
    child.on('close', code => resolve({ code, out, err }));
    child.stdin.end(typeof payload === 'string' ? payload : JSON.stringify(payload));
  });
}

const PAYLOAD = {
  session_id: S,
  model: { model_id: 'claude-opus-4', display_name: 'Opus' },
  context_window: { total_input_tokens: 12345, total_output_tokens: 2500, used_percentage: 42.7, context_window_size: 200000 },
  cost: { total_cost_usd: 0.12, total_duration_ms: 125000, total_lines_added: 10, total_lines_removed: 3 },
  rate_limits: { five_hour: { used_percentage: 12 }, seven_day: { used_percentage: 40 } },
};

const today = () => {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
};

const E = '\x1b[';
const SEP = `${E}2m │ ${E}0m`;

describe('statusline.mjs', () => {
  it('6. prints the bash line: colours, bar, awk rounding', async () => {
    const home = freshHome();
    const { code, out, err } = await render(home, PAYLOAD);
    expect(err).toBe('');
    expect(code).toBe(0);
    expect(out).toBe(
      `${E}36m${E}1m◆${E}0m ${E}37m${E}1mOpus${E}0m${SEP}`
      + `${E}33mctx: 50% ▰▰▰▰▰▱▱▱▱▱${E}0m ${E}2m(84k/167k)${E}0m${SEP}`
      + `${E}35m?${E}0m${SEP}`
      + `${E}2m2m${E}0m${SEP}`
      + `${E}32m+10${E}0m ${E}31m-3${E}0m${SEP}`
      + `${E}2m↑12k ↓2k${E}0m\n`,
    );
  });

  it('1, 2, 3, 5. writes rate-limits.json and a token-stats entry, beside itself, lock released', async () => {
    const home = freshHome();
    const dir = path.join(home, '.dorothy');
    fs.writeFileSync(path.join(dir, 'token-stats.json'), JSON.stringify({ other: { in: 1 } }));
    await render(home, PAYLOAD, { CLAUDE_PROVIDER: 'kimi' });

    expect(fs.readFileSync(path.join(dir, 'rate-limits.json'), 'utf-8'))
      .toBe('{"five_hour":{"used_percentage":12},"seven_day":{"used_percentage":40}}\n');
    const text = fs.readFileSync(path.join(dir, 'token-stats.json'), 'utf-8');
    expect(text.endsWith('}\n')).toBe(true);
    expect(JSON.parse(text)).toEqual({
      other: { in: 1 },
      [S]: { in: 12345, out: 2500, cost: 0.12, model: 'claude-opus-4', extra: false, date: today(), provider: 'kimi' },
    });
    expect(fs.readdirSync(dir).sort()).toEqual(['rate-limits.json', 'statusline-cache', 'token-stats.json']);
  });

  it('2. starts again from {} when the file is not one JSON object, and marks extra usage', async () => {
    const home = freshHome();
    const file = path.join(home, '.dorothy', 'token-stats.json');
    fs.writeFileSync(file, '[1,2');
    await render(home, { ...PAYLOAD, rate_limits: { five_hour: { used_percentage: 101 } } });
    expect(JSON.parse(fs.readFileSync(file, 'utf-8'))).toEqual({
      [S]: { in: 12345, out: 2500, cost: 0.12, model: 'claude-opus-4', extra: true, date: today(), provider: 'claude' },
    });
  });

  it('1, 7. writes no rate limits when there are none, and no entry without a session', async () => {
    const home = freshHome();
    const { session_id: _drop, rate_limits: _none, ...rest } = PAYLOAD;
    void _drop; void _none;
    const { code, out } = await render(home, rest);
    expect(code).toBe(0);
    expect(out).toContain('ctx:');
    expect(fs.readdirSync(path.join(home, '.dorothy'))).toEqual(['statusline-cache']);
  });

  it('7. survives stdin that is not JSON', async () => {
    const home = freshHome();
    const { code, out } = await render(home, 'garbage');
    expect(code).toBe(0);
    expect(out).toContain(`${E}37m${E}1m...${E}0m`);
  });

  it('4. clears a lock older than 5s, and takes it', async () => {
    const home = freshHome();
    const lock = path.join(home, '.dorothy', 'token-stats.lock');
    fs.mkdirSync(lock);
    const old = new Date(Date.now() - 10_000);
    fs.utimesSync(lock, old, old);
    await render(home, PAYLOAD);
    expect(JSON.parse(fs.readFileSync(path.join(home, '.dorothy', 'token-stats.json'), 'utf-8'))).toHaveProperty(S);
    expect(fs.existsSync(lock)).toBe(false);
  });

  it('4. skips its write, and leaves the lock, when another render holds it', async () => {
    const home = freshHome();
    const lock = path.join(home, '.dorothy', 'token-stats.lock');
    fs.mkdirSync(lock);
    const started = Date.now();
    const { out } = await render(home, PAYLOAD);
    expect(Date.now() - started).toBeGreaterThanOrEqual(900);
    expect(out).toContain('ctx:');
    expect(fs.existsSync(path.join(home, '.dorothy', 'token-stats.json'))).toBe(false);
    expect(fs.existsSync(lock)).toBe(true);
  });

  it('4. loses no session when renders run at once', async () => {
    const home = freshHome();
    const ids = Array.from({ length: 6 }, (_, i) => `aaaaaaaa-bbbb-4ccc-8ddd-00000000000${i}`);
    await Promise.all(ids.map(id => render(home, { ...PAYLOAD, session_id: id })));
    const stats = JSON.parse(fs.readFileSync(path.join(home, '.dorothy', 'token-stats.json'), 'utf-8'));
    expect(Object.keys(stats).sort()).toEqual(ids);
  }, 30_000);

  it('9. leaves alone, as it exits, a lock another render took after it released its own', async () => {
    const home = freshHome();
    const lock = path.join(home, '.dorothy', 'token-stats.lock');
    // Loaded before the script, so this exit listener runs before any of the
    // script's own: the moment another render takes the lock between this
    // one's release and its exit, made certain instead of left to timing.
    const takeLock = path.join(home, 'take-lock-at-exit.mjs');
    fs.writeFileSync(takeLock,
      `import { mkdirSync } from 'node:fs';\nprocess.on('exit', () => mkdirSync(${JSON.stringify(lock)}));\n`);
    const { code, err } = await render(home, PAYLOAD, { NODE_OPTIONS: `--import ${pathToFileURL(takeLock).href}` });
    expect(err).toBe('');
    expect(code).toBe(0);
    expect(JSON.parse(fs.readFileSync(path.join(home, '.dorothy', 'token-stats.json'), 'utf-8'))).toHaveProperty(S);
    expect(fs.existsSync(lock)).toBe(true);
  });

  it('6. reads the branch in a git checkout, and caches it in ~/.dorothy', async () => {
    const home = freshHome();
    const repo = path.join(home, 'repo');
    fs.mkdirSync(repo);
    const git = (...a: string[]) => spawnSync('git', a, { cwd: repo, encoding: 'utf8' });
    if (git('init', '-q', '-b', 'feat-x').status !== 0) return;
    git('-c', 'user.email=a@b', '-c', 'user.name=a', 'commit', '-q', '--allow-empty', '-m', 'x');
    const out = await new Promise<string>((resolve, reject) => {
      const child = spawn(process.execPath, [SCRIPT], { cwd: repo, env: { ...process.env, HOME: home, USERPROFILE: home }, windowsHide: true });
      let o = '';
      child.stdout.on('data', d => { o += d; });
      child.on('error', reject);
      child.on('close', () => resolve(o));
      child.stdin.end(JSON.stringify(PAYLOAD));
    });
    expect(out).toContain(`${E}35mfeat-x${E}0m`);
    const cache = fs.readdirSync(path.join(home, '.dorothy', 'statusline-cache'));
    expect(cache).toHaveLength(1);
    expect(cache[0].startsWith('git')).toBe(true);
    expect(cache[0]).not.toMatch(/[\\/:]/);
  });
});

/**
 * Taking over the token-stats lock a dead render left, and releasing one's
 * own, with several renders at once: what the bash status line does since
 * upstream #232 (statusline-lock-takeover.test.ts holds the bash, which does
 * not ship on Windows). The lock is a folder holding its owner's token; a
 * render removes only its own; a lock over 5 s old is taken over by one
 * render at a time, through a takeover folder, and only while it is still the
 * lock that was judged dead.
 *
 * How it fails, the bash test's list held against statusline.mjs, written
 * before statusline.mjs had the takeover (2026-09-28):
 * 10. a render that judged a dead lock stale removes it after another render
 *     has taken it over, and writes beside that render;
 * 11. a render's release removes a lock that is no longer its own;
 * 12. a lock 5 s old is taken for dead;
 * 13. a lock 6 s old, left by a render killed while it held it, is never
 *     taken over, and every render after it skips its write;
 * 14. a render killed while taking a dead lock over leaves something behind
 *     that stops every later takeover;
 * 15. two renders are inside the takeover of the same dead lock at once, so
 *     the one that comes second removes the lock the first has just taken.
 *
 * The bash test puts stand-ins for `date` and `stat` on the PATH. Here the
 * same moments are reached through a module loaded before the script
 * (NODE_OPTIONS --import), which patches fs and Date.now in that render only:
 * - HOLD_AS: the read of token-stats.json, made with the lock held, says so
 *   (<HOLD_AS>.holds) and waits there until told to go (<HOLD_AS>.go or
 *   all.go); the render says when it ends (<HOLD_AS>.ended);
 * - FREEZE_NOW: the time it reads, in seconds, so an age is exact however
 *   loaded the machine is;
 * - INTERLEAVE / KILL_AT: at that read of the lock's age (fs.statSync of the
 *   lock folder, counted in lock-stats), render A comes in (a.json, HOLD_AS=A,
 *   its clock frozen at that moment) and takes the lock over or ends; or this
 *   render is killed there.
 */
const PRELOAD = `
import { createRequire, syncBuiltinESMExports } from 'node:module';
import { spawn } from 'node:child_process';
const require = createRequire(import.meta.url);
const fs = require('node:fs');
const path = require('node:path');
const env = process.env;
const home = env.HOME;
const at = name => path.join(home, name);
const sleep = ms => Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
const waitFor = (names, ms = 30000) => { for (let n = 0; n < ms / 50 && !names.some(x => fs.existsSync(at(x))); n++) sleep(50); };
const realNow = Date.now.bind(Date);
if (env.FREEZE_NOW) Date.now = () => Number(env.FREEZE_NOW) * 1000;
const lock = path.join(home, '.dorothy', 'token-stats.lock');
const statSync = fs.statSync;
fs.statSync = function (p, ...rest) {
  if (String(p) !== lock) return statSync.call(fs, p, ...rest);
  const before = statSync.call(fs, p, ...rest);
  const count = Number(fs.existsSync(at('lock-stats')) ? fs.readFileSync(at('lock-stats'), 'utf8') : 0) + 1;
  fs.writeFileSync(at('lock-stats'), String(count));
  if (env.KILL_AT === String(count)) process.kill(process.pid, 'SIGKILL');
  if (env.INTERLEAVE === String(count)) {
    const now = env.FREEZE_NOW || String(Math.floor(realNow() / 1000));
    spawn(process.execPath, [env.SCRIPT], {
      cwd: home, detached: true, windowsHide: true,
      stdio: [fs.openSync(at('a.json'), 'r'), 'ignore', 'ignore'],
      env: { ...env, INTERLEAVE: '', KILL_AT: '', HOLD_AS: 'A', FREEZE_NOW: now },
    }).unref();
    waitFor(['A.holds', 'A.ended']);
  }
  return before;
};
const readFileSync = fs.readFileSync;
fs.readFileSync = function (p, ...rest) {
  if (env.HOLD_AS && String(p).endsWith('token-stats.json')) {
    fs.writeFileSync(at(env.HOLD_AS + '.holds'), '');
    waitFor([env.HOLD_AS + '.go', 'all.go']);
  }
  return readFileSync.call(fs, p, ...rest);
};
syncBuiltinESMExports();
if (env.HOLD_AS) process.on('exit', () => { try { fs.writeFileSync(at(env.HOLD_AS + '.ended'), ''); } catch { /* its HOME is gone */ } });
`;

describe('statusline.mjs: taking over the token-stats lock, and releasing it', () => {
  const children: ChildProcess[] = [];
  const homes: string[] = [];
  afterEach(async () => {
    for (const home of homes) fs.writeFileSync(path.join(home, 'all.go'), '');
    for (const child of children.splice(0)) if (child.exitCode === null && child.signalCode === null) child.kill('SIGKILL');
    // A render let go by all.go ends within moments: give it those.
    await new Promise(resolve => setTimeout(resolve, 300));
    homes.length = 0;
  });

  const sessionInput = (session: string) => JSON.stringify({ ...PAYLOAD, session_id: session });

  async function until(condition: () => boolean, what: string, ms = 20_000): Promise<void> {
    const end = Date.now() + ms;
    while (!condition()) {
      if (Date.now() > end) throw new Error(`timed out waiting for ${what}`);
      await new Promise(resolve => setTimeout(resolve, 50));
    }
  }

  function bench() {
    const home = freshHome();
    homes.push(home);
    const dorothy = path.join(home, '.dorothy');
    const preload = path.join(home, 'preload.mjs');
    fs.writeFileSync(preload, PRELOAD);
    const lock = path.join(dorothy, 'token-stats.lock');
    const stats = path.join(dorothy, 'token-stats.json');
    const at = (name: string) => path.join(home, name);
    const env = (extra: Record<string, string>) => ({ SCRIPT, NODE_OPTIONS: `--import ${pathToFileURL(preload).href}`, ...extra });

    /** A render run to its end. */
    const renderTo = (session: string, extra: Record<string, string> = {}) => render(home, sessionInput(session), env(extra));

    /** A render left running. */
    const start = (session: string, extra: Record<string, string> = {}) => {
      const cleanEnv: NodeJS.ProcessEnv = {};
      for (const [k, v] of Object.entries(process.env)) if (!/^(CLAUDE_|DOROTHY_)/.test(k)) cleanEnv[k] = v;
      const child = spawn(process.execPath, [SCRIPT], {
        cwd: home, env: { ...cleanEnv, HOME: home, USERPROFILE: home, ...env(extra) }, stdio: ['pipe', 'ignore', 'ignore'], windowsHide: true,
      });
      children.push(child);
      child.stdin!.end(sessionInput(session));
      return child;
    };
    const ended = (child: ChildProcess) => until(() => child.exitCode !== null || child.signalCode !== null, 'a render to end');

    /** Every file and folder the lock is made of, backdated to a whole second. Returns that second. */
    const backdate = (seconds: number): number => {
      const second = Math.floor(Date.now() / 1000) - seconds;
      const when = new Date(second * 1000);
      const walk = (entry: string): void => {
        if (fs.statSync(entry).isDirectory()) for (const name of fs.readdirSync(entry)) walk(path.join(entry, name));
        fs.utimesSync(entry, when, when);
      };
      for (const name of fs.readdirSync(dorothy)) if (name.startsWith('token-stats.lock')) walk(path.join(dorothy, name));
      return second;
    };

    /** A render killed while it holds the lock, `seconds` ago. Returns the lock's time, in seconds. */
    const deadHolder = async (seconds: number): Promise<number> => {
      const child = start('sK', { HOLD_AS: 'K' });
      await until(() => fs.existsSync(at('K.holds')), 'render K to hold the lock');
      child.kill('SIGKILL');
      await ended(child);
      return backdate(seconds);
    };

    const sessions = (): string[] => (fs.existsSync(stats) ? Object.keys(JSON.parse(fs.readFileSync(stats, 'utf-8'))) : []);
    const ageReads = (): number => Number(fs.existsSync(at('lock-stats')) ? fs.readFileSync(at('lock-stats'), 'utf8') : 0);

    return { home, lock, at, renderTo, start, ended, backdate, deadHolder, sessions, ageReads };
  }

  it('10. a render that judged a dead lock stale leaves it to the render that took it over first', async () => {
    const b = bench();
    await b.deadHolder(60);
    fs.writeFileSync(b.at('a.json'), sessionInput('sA'));

    const run = await b.renderTo('sB', { INTERLEAVE: '1' });

    expect(run.code, run.err).toBe(0);
    expect(fs.existsSync(b.at('A.holds')), 'render A never took the lock over').toBe(true);
    expect(fs.existsSync(b.lock), "render A's lock was removed while A held it").toBe(true);
    expect(b.sessions(), 'render B wrote beside render A').not.toContain('sB');

    fs.writeFileSync(b.at('A.go'), '');
    await until(() => !fs.existsSync(b.lock) && b.sessions().includes('sA'), 'render A to write and release');
  }, 60_000);

  it('10b. and so when the lock taken over is itself over 5 s old by the time it looks again: it is not the one judged dead', async () => {
    // Render B's clock a minute ahead: the lock render A takes over reads as
    // old as the dead one did, and only its owner tells them apart.
    const b = bench();
    await b.deadHolder(60);
    fs.writeFileSync(b.at('a.json'), sessionInput('sA'));

    const run = await b.renderTo('sB', { INTERLEAVE: '1', FREEZE_NOW: String(Math.floor(Date.now() / 1000) + 60) });

    expect(run.code, run.err).toBe(0);
    expect(fs.existsSync(b.at('A.holds')), 'render A never took the lock over').toBe(true);
    expect(fs.existsSync(b.lock), "render A's lock was removed while A held it").toBe(true);
    expect(b.sessions(), 'render B wrote beside render A').not.toContain('sB');

    fs.writeFileSync(b.at('A.go'), '');
    await until(() => !fs.existsSync(b.lock) && b.sessions().includes('sA'), 'render A to write and release');
  }, 60_000);

  it('11. a render slow past 5 s leaves, as it releases, the lock another render took over from it', async () => {
    const b = bench();
    const slow = b.start('sS', { HOLD_AS: 'S' });
    await until(() => fs.existsSync(b.at('S.holds')), 'render S to hold the lock');
    b.backdate(60);
    const taker = b.start('sT', { HOLD_AS: 'T' });
    await until(() => fs.existsSync(b.at('T.holds')), 'render T to take the lock over');

    fs.writeFileSync(b.at('S.go'), '');
    await b.ended(slow);

    expect(fs.existsSync(b.lock), "render S's release removed render T's lock").toBe(true);
    fs.writeFileSync(b.at('T.go'), '');
    await b.ended(taker);
    expect(fs.existsSync(b.lock)).toBe(false);
    // T read the file before S wrote, so T's write replaces S's: what a lock
    // taken from a render still alive costs. The release is what is tested.
    expect(b.sessions()).toContain('sT');
  }, 60_000);

  it('12. a lock 5 s old is not taken for dead', async () => {
    const b = bench();
    const since = await b.deadHolder(60);

    const run = await b.renderTo('sB', { FREEZE_NOW: String(since + 5) });

    expect(run.code, run.err).toBe(0);
    expect(b.sessions()).not.toContain('sB');
    expect(fs.existsSync(b.lock)).toBe(true);
  }, 60_000);

  it('13. a lock 6 s old, its holder dead, is taken over', async () => {
    const b = bench();
    const since = await b.deadHolder(60);

    const run = await b.renderTo('sB', { FREEZE_NOW: String(since + 6) });

    expect(run.code, run.err).toBe(0);
    expect(b.sessions()).toContain('sB');
    expect(fs.existsSync(b.lock)).toBe(false);
  }, 60_000);

  it('14. a render killed while taking a dead lock over does not stop the next takeover', async () => {
    const b = bench();
    await b.deadHolder(60);
    // Killed at its second read of the lock's age: when there is one, it is
    // taken in the middle of the takeover.
    const killed = b.start('sR', { KILL_AT: '2' });
    await b.ended(killed);
    expect(b.ageReads(), 'the render never read the age a second time').toBe(2);
    fs.rmSync(b.at('lock-stats'), { force: true });
    b.backdate(60);

    const run = await b.renderTo('sN');

    expect(run.code, run.err).toBe(0);
    expect(b.sessions()).toContain('sN');
    expect(fs.readdirSync(path.dirname(b.lock)).filter(name => name.startsWith('token-stats.lock')), 'left behind').toEqual([]);
  }, 60_000);

  it('15. a render that comes in while another is taking the dead lock over leaves the takeover to it', async () => {
    const b = bench();
    await b.deadHolder(60);
    fs.writeFileSync(b.at('a.json'), sessionInput('sA'));

    // Render A comes in at render B's second read of the lock's age: when
    // there is one, B is in the middle of its takeover.
    const run = await b.renderTo('sB', { INTERLEAVE: '2' });

    expect(run.code, run.err).toBe(0);
    expect(b.ageReads(), 'render B never read the age a second time').toBeGreaterThanOrEqual(2);
    expect(fs.existsSync(b.at('A.holds')), 'render A took the lock over while render B was taking it over').toBe(false);
    expect(b.sessions()).toContain('sB');
    await until(() => !fs.existsSync(b.lock), 'the lock to be released');
  }, 60_000);
});
