import { describe, it, expect, afterAll } from 'vitest';
import { spawn, spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

/**
 * hooks/statusline.mjs: the Claude Code status line on Windows (audit A15),
 * doing what the bash one generated by electron/utils/statusline.ts does. The
 * Usage page reads the two files it writes, so on Windows its figures stayed
 * empty while the bash one could not run.
 *
 * How it can fail, written before it existed:
 *  1. rate-limits.json not written, or not as the bash one writes it (the
 *     compact `rate_limits` object and a newline), or written when absent.
 *  2. token-stats.json entry not {in, out, cost, model, extra, date,
 *     provider}; other sessions lost; a file that is not one JSON object not
 *     started again from {}.
 *  3. Written in place rather than beside itself and renamed; a tmp left over.
 *  4. The lock ignored: concurrent renders lose each other's sessions. A lock
 *     older than 5s never cleared. A fresh lock held by another render
 *     overridden instead of skipping this write, as the bash does.
 *  5. Its own lock left behind.
 *  6. A status line other than the bash one (colours, bar, rounding: awk
 *     prints 2500 tokens as "2k", round-half-even, not "3k").
 *  7. A crash on missing fields, or a token-stats entry for no session.
 *  8. Anything written outside ~/.dorothy of the HOME it runs in.
 */

const SCRIPT = path.join(__dirname, '../../hooks/statusline.mjs');
const S = 'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee';
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'tars-statusline-'));
afterAll(() => fs.rmSync(tmp, { recursive: true, force: true }));

function freshHome(): string {
  const home = fs.mkdtempSync(path.join(tmp, 'home-'));
  fs.mkdirSync(path.join(home, '.dorothy'));
  return home;
}

function render(home: string, payload: unknown, env: Record<string, string> = {}): Promise<{ code: number | null; out: string; err: string }> {
  return new Promise((resolve, reject) => {
    const cleanEnv: NodeJS.ProcessEnv = {};
    for (const [k, v] of Object.entries(process.env)) if (!/^(CLAUDE_|DOROTHY_)/.test(k)) cleanEnv[k] = v;
    const child = spawn(process.execPath, [SCRIPT], {
      cwd: home,
      env: { ...cleanEnv, HOME: home, USERPROFILE: home, ...env },
      windowsHide: true,
    });
    let out = '';
    let err = '';
    child.stdout.setEncoding('utf8');
    child.stderr.setEncoding('utf8');
    child.stdout.on('data', d => { out += d; });
    child.stderr.on('data', d => { err += d; });
    child.on('error', reject);
    child.on('close', code => resolve({ code, out, err }));
    child.stdin.end(typeof payload === 'string' ? payload : JSON.stringify(payload));
  });
}

const PAYLOAD = {
  session_id: S,
  model: { model_id: 'claude-opus-4', display_name: 'Opus' },
  context_window: { total_input_tokens: 12345, total_output_tokens: 2500, used_percentage: 42.7, context_window_size: 200000 },
  cost: { total_cost_usd: 0.12, total_duration_ms: 125000, total_lines_added: 10, total_lines_removed: 3 },
  rate_limits: { five_hour: { used_percentage: 12 }, seven_day: { used_percentage: 40 } },
};

const today = () => {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
};

const E = '\x1b[';
const SEP = `${E}2m │ ${E}0m`;

describe('statusline.mjs', () => {
  it('6. prints the bash line: colours, bar, awk rounding', async () => {
    const home = freshHome();
    const { code, out, err } = await render(home, PAYLOAD);
    expect(err).toBe('');
    expect(code).toBe(0);
    expect(out).toBe(
      `${E}36m${E}1m◆${E}0m ${E}37m${E}1mOpus${E}0m${SEP}`
      + `${E}33mctx: 50% ▰▰▰▰▰▱▱▱▱▱${E}0m ${E}2m(84k/167k)${E}0m${SEP}`
      + `${E}35m?${E}0m${SEP}`
      + `${E}2m2m${E}0m${SEP}`
      + `${E}32m+10${E}0m ${E}31m-3${E}0m${SEP}`
      + `${E}2m↑12k ↓2k${E}0m\n`,
    );
  });

  it('1, 2, 3, 5. writes rate-limits.json and a token-stats entry, beside itself, lock released', async () => {
    const home = freshHome();
    const dir = path.join(home, '.dorothy');
    fs.writeFileSync(path.join(dir, 'token-stats.json'), JSON.stringify({ other: { in: 1 } }));
    await render(home, PAYLOAD, { CLAUDE_PROVIDER: 'kimi' });

    expect(fs.readFileSync(path.join(dir, 'rate-limits.json'), 'utf-8'))
      .toBe('{"five_hour":{"used_percentage":12},"seven_day":{"used_percentage":40}}\n');
    const text = fs.readFileSync(path.join(dir, 'token-stats.json'), 'utf-8');
    expect(text.endsWith('}\n')).toBe(true);
    expect(JSON.parse(text)).toEqual({
      other: { in: 1 },
      [S]: { in: 12345, out: 2500, cost: 0.12, model: 'claude-opus-4', extra: false, date: today(), provider: 'kimi' },
    });
    expect(fs.readdirSync(dir).sort()).toEqual(['rate-limits.json', 'statusline-cache', 'token-stats.json']);
  });

  it('2. starts again from {} when the file is not one JSON object, and marks extra usage', async () => {
    const home = freshHome();
    const file = path.join(home, '.dorothy', 'token-stats.json');
    fs.writeFileSync(file, '[1,2');
    await render(home, { ...PAYLOAD, rate_limits: { five_hour: { used_percentage: 101 } } });
    expect(JSON.parse(fs.readFileSync(file, 'utf-8'))).toEqual({
      [S]: { in: 12345, out: 2500, cost: 0.12, model: 'claude-opus-4', extra: true, date: today(), provider: 'claude' },
    });
  });

  it('1, 7. writes no rate limits when there are none, and no entry without a session', async () => {
    const home = freshHome();
    const { session_id: _drop, rate_limits: _none, ...rest } = PAYLOAD;
    void _drop; void _none;
    const { code, out } = await render(home, rest);
    expect(code).toBe(0);
    expect(out).toContain('ctx:');
    expect(fs.readdirSync(path.join(home, '.dorothy'))).toEqual(['statusline-cache']);
  });

  it('7. survives stdin that is not JSON', async () => {
    const home = freshHome();
    const { code, out } = await render(home, 'garbage');
    expect(code).toBe(0);
    expect(out).toContain(`${E}37m${E}1m...${E}0m`);
  });

  it('4. clears a lock older than 5s, and takes it', async () => {
    const home = freshHome();
    const lock = path.join(home, '.dorothy', 'token-stats.lock');
    fs.mkdirSync(lock);
    const old = new Date(Date.now() - 10_000);
    fs.utimesSync(lock, old, old);
    await render(home, PAYLOAD);
    expect(JSON.parse(fs.readFileSync(path.join(home, '.dorothy', 'token-stats.json'), 'utf-8'))).toHaveProperty(S);
    expect(fs.existsSync(lock)).toBe(false);
  });

  it('4. skips its write, and leaves the lock, when another render holds it', async () => {
    const home = freshHome();
    const lock = path.join(home, '.dorothy', 'token-stats.lock');
    fs.mkdirSync(lock);
    const started = Date.now();
    const { out } = await render(home, PAYLOAD);
    expect(Date.now() - started).toBeGreaterThanOrEqual(900);
    expect(out).toContain('ctx:');
    expect(fs.existsSync(path.join(home, '.dorothy', 'token-stats.json'))).toBe(false);
    expect(fs.existsSync(lock)).toBe(true);
  });

  it('4. loses no session when renders run at once', async () => {
    const home = freshHome();
    const ids = Array.from({ length: 6 }, (_, i) => `aaaaaaaa-bbbb-4ccc-8ddd-00000000000${i}`);
    await Promise.all(ids.map(id => render(home, { ...PAYLOAD, session_id: id })));
    const stats = JSON.parse(fs.readFileSync(path.join(home, '.dorothy', 'token-stats.json'), 'utf-8'));
    expect(Object.keys(stats).sort()).toEqual(ids);
  }, 30_000);

  it('6. reads the branch in a git checkout, and caches it in ~/.dorothy', async () => {
    const home = freshHome();
    const repo = path.join(home, 'repo');
    fs.mkdirSync(repo);
    const git = (...a: string[]) => spawnSync('git', a, { cwd: repo, encoding: 'utf8' });
    if (git('init', '-q', '-b', 'feat-x').status !== 0) return;
    git('-c', 'user.email=a@b', '-c', 'user.name=a', 'commit', '-q', '--allow-empty', '-m', 'x');
    const out = await new Promise<string>((resolve, reject) => {
      const child = spawn(process.execPath, [SCRIPT], { cwd: repo, env: { ...process.env, HOME: home, USERPROFILE: home }, windowsHide: true });
      let o = '';
      child.stdout.on('data', d => { o += d; });
      child.on('error', reject);
      child.on('close', () => resolve(o));
      child.stdin.end(JSON.stringify(PAYLOAD));
    });
    expect(out).toContain(`${E}35mfeat-x${E}0m`);
    const cache = fs.readdirSync(path.join(home, '.dorothy', 'statusline-cache'));
    expect(cache).toHaveLength(1);
    expect(cache[0].startsWith('git')).toBe(true);
    expect(cache[0]).not.toMatch(/[\\/:]/);
  });
});
