#!/usr/bin/env node
// The Claude Code status line in Node: what the bash one generated by
// electron/utils/statusline.ts does, for Windows, where bash, jq, awk and
// `stat -f/-c` are not there (audit A15). Configured on win32 only; the bash
// script stays what macOS and Linux run, and remains the reference.
//
// It renders the same line and writes the same two files the Usage page reads:
// ~/.dorothy/rate-limits.json (the `rate_limits` object as Claude Code sent
// it) and ~/.dorothy/token-stats.json (one entry per session), the second
// under the same mkdir lock, written beside itself and renamed over.
//
// Where it differs on purpose: the git-branch cache file name replaces `\`
// and `:` as well as `/`, which a Windows file name cannot hold.

import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

const DATA_DIR = path.join(os.homedir(), '.dorothy');

function readStdin() {
  return new Promise(resolve => {
    const chunks = [];
    process.stdin.on('data', c => chunks.push(c));
    process.stdin.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    process.stdin.on('error', () => resolve(''));
  });
}

const sleepSync = ms => Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);

/** jq `a // b`: b when a is null or false (or absent). */
const or = (value, fallback) => (value === undefined || value === null || value === false ? fallback : value);
/** jq `.a.b`, null through anything that is not an object (the whole jq pass fails on that: see fields()). */
function at(input, ...keys) {
  let current = input;
  for (const key of keys) {
    if (current === null || current === undefined) return null;
    if (typeof current !== 'object' || Array.isArray(current)) throw new Error('jq: cannot index');
    current = Object.prototype.hasOwnProperty.call(current, key) ? current[key] : null;
  }
  return current ?? null;
}

/** jq @tsv of one value: strings escaped, numbers and booleans as jq prints them. */
function tsv(value) {
  const text = typeof value === 'string' ? value : JSON.stringify(value);
  return text.replace(/\\/g, '\\\\').replace(/\t/g, '\\t').replace(/\n/g, '\\n').replace(/\r/g, '\\r');
}

/**
 * The one jq pass of the bash script, and its `IFS=$'\t' read -r` into
 * fourteen names: a tab is IFS whitespace, so runs of tabs are one separator
 * and empty fields vanish, shifting the rest, exactly as bash reads them.
 */
function fields(text) {
  let line = '';
  try {
    const input = JSON.parse(text);
    const values = [
      or(at(input, 'session_id'), ''),
      or(at(input, 'context_window', 'total_input_tokens'), 0),
      or(at(input, 'context_window', 'total_output_tokens'), 0),
      or(at(input, 'cost', 'total_cost_usd'), 0),
      or(at(input, 'model', 'model_id'), or(at(input, 'model', 'display_name'), 'unknown')),
      or(at(input, 'rate_limits', 'five_hour', 'used_percentage'), 0),
      or(at(input, 'rate_limits', 'seven_day', 'used_percentage'), 0),
      or(at(input, 'model', 'display_name'), '...'),
      or(at(input, 'context_window', 'used_percentage'), 0),
      or(at(input, 'context_window', 'context_window_size'), 200000),
      or(at(input, 'cost', 'total_duration_ms'), 0),
      or(at(input, 'cost', 'total_lines_added'), 0),
      or(at(input, 'cost', 'total_lines_removed'), 0),
    ];
    const rateLimits = at(input, 'rate_limits');
    if (rateLimits !== null && rateLimits !== false) values.push(JSON.stringify(rateLimits));
    line = values.map(tsv).join('\t');
  } catch {
    line = '';
  }
  const parts = line.replace(/^\t+|\t+$/g, '').split(/\t+/).filter(p => p !== '');
  const names = ['SESSION_ID', 'T_IN', 'T_OUT', 'T_COST', 'T_MODEL', 'PCT_5H', 'PCT_7D', 'MODEL', 'RAW_PCT_RAW',
    'CTX_MAX', 'DURATION_MS', 'LINES_ADDED', 'LINES_REMOVED', 'RATE_LIMITS'];
  const out = {};
  names.forEach((name, i) => {
    out[name] = i < names.length - 1 ? (parts[i] ?? '') : parts.slice(i).join('\t');
  });
  const defaults = { T_IN: '0', T_OUT: '0', T_COST: '0', T_MODEL: 'unknown', PCT_5H: '0', PCT_7D: '0', MODEL: '...',
    RAW_PCT_RAW: '0', CTX_MAX: '200000', DURATION_MS: '0', LINES_ADDED: '0', LINES_REMOVED: '0' };
  for (const [name, value] of Object.entries(defaults)) if (out[name] === '') out[name] = value;
  return out;
}

/** awk's reading of a string as a number: its leading numeric prefix, else 0. */
function awkNum(text) {
  const m = /^\s*[-+]?(\d+\.?\d*|\.\d+)([eE][-+]?\d+)?/.exec(String(text));
  return m ? Number(m[0]) : 0;
}
const looksNumeric = text => /^\s*[-+]?(\d+\.?\d*|\.\d+)([eE][-+]?\d+)?\s*$/.test(String(text));
/** awk `a > 100`: numeric when a looks like a number, else a string comparison with "100". */
const awkGreater100 = a => (looksNumeric(a) ? awkNum(a) > 100 : String(a) > '100');

/** printf "%.Nf": correct rounding of the double, ties to even as C does. */
function cFixed(x, digits) {
  const exact = x.toFixed(20);
  const m = new RegExp(`^(-?\\d+)\\.(\\d{${digits}})5(0*)$`).exec(exact);
  if (m) {
    const scaled = BigInt(m[1] + m[2]);
    const abs = scaled < 0n ? -scaled : scaled;
    const rounded = abs % 2n === 0n ? scaled : scaled + (scaled < 0n ? -1n : 1n);
    const s = (rounded < 0n ? -rounded : rounded).toString().padStart(digits + 1, '0');
    const sign = rounded < 0n || (rounded === 0n && x < 0) ? '-' : '';
    return digits === 0 ? `${sign}${s}` : `${sign}${s.slice(0, -digits)}.${s.slice(-digits)}`;
  }
  return x.toFixed(digits);
}

/** bash `$(( a ))` integer, or the script's `set -e` exit when it is not one. */
function bashInt(text) {
  if (!/^\s*-?\d+\s*$/.test(String(text))) throw new BashArithmeticError();
  return Number.parseInt(text, 10);
}
class BashArithmeticError extends Error {}

function writeRateLimits(rateLimits) {
  if (rateLimits === '' || rateLimits === 'null') return;
  try {
    fs.writeFileSync(path.join(DATA_DIR, 'rate-limits.json'), `${rateLimits}\n`);
  } catch {
    // echo ... > file 2>/dev/null || true
  }
}

function localDate() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

/** The mkdir lock of the bash script: 20 tries 50ms apart, a lock older than 5s cleared once. */
function acquireLock(lockDir) {
  for (let i = 0; i < 20; i++) {
    try {
      fs.mkdirSync(lockDir);
      return true;
    } catch {
      sleepSync(50);
    }
  }
  try {
    const st = fs.statSync(lockDir);
    if (st.isDirectory() && (Date.now() - st.mtimeMs) / 1000 > 5) {
      try { fs.rmdirSync(lockDir); } catch { /* || true */ }
      try { fs.mkdirSync(lockDir); return true; } catch { return false; }
    }
  } catch {
    // no lock dir at all: the bash `[ -d ]` is false too
  }
  return false;
}

/** mv over the file; on Windows a reader holding it open can make that fail for a moment. */
function renameOver(from, to) {
  for (let i = 0; i < 5; i++) {
    try {
      fs.renameSync(from, to);
      return true;
    } catch (error) {
      if (process.platform !== 'win32' || !['EPERM', 'EBUSY', 'EACCES'].includes(error?.code)) return false;
      sleepSync(20);
    }
  }
  return false;
}

function writeTokenStats(f) {
  if (!f.SESSION_ID) return;
  const extra = awkGreater100(f.PCT_5H) || awkGreater100(f.PCT_7D);
  const lockDir = path.join(DATA_DIR, 'token-stats.lock');
  if (!acquireLock(lockDir)) return;
  const release = () => { try { fs.rmdirSync(lockDir); } catch { /* || true */ } };
  process.once('exit', release);
  try {
    const file = path.join(DATA_DIR, 'token-stats.json');
    let existing = '';
    try { existing = fs.readFileSync(file, 'utf8'); } catch { /* || true */ }
    let tin, tout, cost;
    try {
      // --argjson: each must be one JSON value, or jq fails and nothing is written.
      [tin, tout, cost] = [f.T_IN, f.T_OUT, f.T_COST].map(v => JSON.parse(v));
    } catch {
      return;
    }
    let stats;
    try { stats = JSON.parse(existing); } catch { stats = {}; }
    if (stats === null || typeof stats !== 'object' || Array.isArray(stats)) stats = {};
    stats[f.SESSION_ID] = {
      in: tin, out: tout, cost, model: f.T_MODEL, extra, date: localDate(), provider: process.env.CLAUDE_PROVIDER || 'claude',
    };
    const tmp = `${file}.tmp.${process.pid}`;
    try {
      fs.writeFileSync(tmp, `${JSON.stringify(stats)}\n`);
      if (!renameOver(tmp, file)) fs.rmSync(tmp, { force: true });
    } catch {
      try { fs.rmSync(tmp, { force: true }); } catch { /* rm -f */ }
    }
  } finally {
    release();
  }
}

function gitBranch() {
  const cacheDir = path.join(DATA_DIR, 'statusline-cache');
  try { fs.mkdirSync(cacheDir, { recursive: true, mode: 0o700 }); } catch { /* || true */ }
  try { fs.chmodSync(cacheDir, 0o700); } catch { /* || true */ }
  const cache = path.join(cacheDir, `git${process.cwd().replace(/[\\/:]/g, '_')}`);
  let branch = '?';
  try {
    const st = fs.lstatSync(cache);
    if (st.isFile() && (Date.now() - st.mtimeMs) / 1000 < 5) branch = fs.readFileSync(cache, 'utf8').replace(/\n+$/, '');
  } catch {
    // no cache yet
  }
  if (branch === '?') {
    try {
      branch = execFileSync('git', ['rev-parse', '--abbrev-ref', 'HEAD'], { stdio: ['ignore', 'pipe', 'ignore'], windowsHide: true })
        .toString('utf8').replace(/\n+$/, '').replace(/\r$/, '');
      if (branch === '') branch = '?';
    } catch {
      branch = '?';
    }
    let isLink = false;
    try { isLink = fs.lstatSync(cache).isSymbolicLink(); } catch { /* absent */ }
    if (!isLink) {
      try { fs.writeFileSync(cache, `${branch}\n`); } catch { /* || true */ }
    }
  }
  return branch;
}

function formatDuration(ms) {
  const totalSec = Math.trunc(ms / 1000);
  const hours = Math.trunc(totalSec / 3600);
  const mins = Math.trunc((totalSec % 3600) / 60);
  if (hours > 0) return `${hours}h${mins}m`;
  if (mins > 0) return `${mins}m`;
  return `${totalSec}s`;
}

function formatTokens(tokens) {
  // `[ "$tokens" -ge ... ]` on something that is not an integer is false (and
  // an error on stderr): the value is printed as it is.
  if (!/^\s*-?\d+\s*$/.test(String(tokens))) return String(tokens);
  const n = Number.parseInt(tokens, 10);
  if (n >= 1000000) return `${cFixed(n / 1000000, 1)}M`;
  if (n >= 1000) return `${cFixed(n / 1000, 0)}k`;
  return String(tokens);
}

const RESET = '\x1b[0m';
const DIM = '\x1b[2m';
const BOLD = '\x1b[1m';
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const RED = '\x1b[31m';
const CYAN = '\x1b[36m';
const MAGENTA = '\x1b[35m';
const WHITE = '\x1b[37m';
const AUTOCOMPACT_BUFFER = 33000;

function render(f) {
  const rawPct = Math.trunc(awkNum(f.RAW_PCT_RAW));
  const ctxUsed = Math.trunc((rawPct * awkNum(f.CTX_MAX)) / 100);
  const ctxUsable = bashInt(f.CTX_MAX) - AUTOCOMPACT_BUFFER;
  if (ctxUsable === 0) throw new BashArithmeticError(); // awk: division by zero
  const ctxPct = Math.trunc((ctxUsed * 100) / ctxUsable);
  const branch = gitBranch();
  const duration = formatDuration(bashInt(f.DURATION_MS));
  const ctxUsedFmt = formatTokens(String(ctxUsed));
  const ctxUsableFmt = formatTokens(String(ctxUsable));
  const inFmt = formatTokens(f.T_IN);
  const outFmt = formatTokens(f.T_OUT);
  const ctxColor = ctxPct >= 80 ? RED : ctxPct >= 50 ? YELLOW : GREEN;
  let filled = Math.trunc(ctxPct / 10);
  if (filled > 10) filled = 10;
  const empty = 10 - filled;
  const bar = '▰'.repeat(Math.max(0, filled)) + '▱'.repeat(Math.max(0, empty));
  const sep = `${DIM} │ ${RESET}`;
  return `${CYAN}${BOLD}◆${RESET} ${WHITE}${BOLD}${f.MODEL}${RESET}${sep}`
    + `${ctxColor}ctx: ${ctxPct}% ${bar}${RESET} ${DIM}(${ctxUsedFmt}/${ctxUsableFmt})${RESET}${sep}`
    + `${MAGENTA}${branch}${RESET}${sep}`
    + `${DIM}${duration}${RESET}${sep}`
    + `${GREEN}+${f.LINES_ADDED}${RESET} ${RED}-${f.LINES_REMOVED}${RESET}${sep}`
    + `${DIM}↑${inFmt} ↓${outFmt}${RESET}\n`;
}

const f = fields(await readStdin());
writeRateLimits(f.RATE_LIMITS);
writeTokenStats(f);
let line = '';
let code = 0;
try {
  line = render(f);
} catch (error) {
  // The bash script runs under `set -e`: a value its arithmetic cannot take
  // ends it there, with nothing printed. Anything else is a bug: say so.
  if (!(error instanceof BashArithmeticError)) process.stderr.write(`statusline: ${error?.stack ?? error}\n`);
  code = error instanceof BashArithmeticError ? 2 : 1;
}
if (line) process.stdout.write(line, () => process.exit(code));
else process.exit(code);
